export const GAME_CONFIG = Object.freeze({
  BOARD_COLUMNS: 20,
  BOARD_ROWS: 20,
  INITIAL_SNAKE_LENGTH: 3,
  INITIAL_INTERVAL_MS: 150,
  MIN_INTERVAL_MS: 60,
  INTERVAL_STEP_MS: 10,
  FOOD_PER_LEVEL: 5,
  POINTS_PER_FOOD: 10,
  MAX_FRAME_DELTA_MS: 250,
  HIGH_SCORE_STORAGE_KEY: 'snake-game:high-score',
});
